services:
  flask-app:
    image: achebeh/community-challenge-backend 
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 5000:5000

  vue-app:
    image: achebeh/community-challenge-frontend 
    # build:
    #   context: ./frontend
    #   dockerfile: Dockerfile
    env_file:
      - .env
    ports:
    - 80:80